//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessTheNumber.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuessTheNumber.Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email is already registered on the app.
        /// </summary>
        public static string GuessTheNumberEmailAlreadyExistsException {
            get {
                return ResourceManager.GetString("GuessTheNumberEmailAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application logic failed.
        /// </summary>
        public static string GuessTheNumberException {
            get {
                return ResourceManager.GetString("GuessTheNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current game is already finished.
        /// </summary>
        public static string GuessTheNumberGameOverException {
            get {
                return ResourceManager.GetString("GuessTheNumberGameOverException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password was entered.
        /// </summary>
        public static string GuessTheNumberInvalidPasswordException {
            get {
                return ResourceManager.GetString("GuessTheNumberInvalidPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active game right now.
        /// </summary>
        public static string GuessTheNumberNoActiveGameException {
            get {
                return ResourceManager.GetString("GuessTheNumberNoActiveGameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making attempt on one&apos;s own game is not allowed.
        /// </summary>
        public static string GuessTheNumberOwnerAttemptException {
            get {
                return ResourceManager.GetString("GuessTheNumberOwnerAttemptException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this username or email is not registered on the app..
        /// </summary>
        public static string GuessTheNumberUserDoesNotExistException {
            get {
                return ResourceManager.GetString("GuessTheNumberUserDoesNotExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this username is already registered on the app.
        /// </summary>
        public static string GuessTheNumberUsernameAlreadyExistsException {
            get {
                return ResourceManager.GetString("GuessTheNumberUsernameAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not registrered on the app.
        /// </summary>
        public static string GuessTheNumberUserWasNotCreatedException {
            get {
                return ResourceManager.GetString("GuessTheNumberUserWasNotCreatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong on the server side. Try again later.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occured.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
